title: Audio Project
description: Basic notes on my audio project
theme: just-the-docs

url: https://mathnerd314.github.io/audio-project/

defaults:
  - scope:
      path: "docs" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"
